version: 0.2 # 0.2 권장

phases: # 빌드 단계
  install:
    runtime-versions:
      # https://docs.aws.amazon.com/codebuild/latest/userguide/runtime-versions.html
      java: corretto21
  build:
    commands:
      - echo Build started on `date`
      - ./gradlew -Pprod clean bootJar
      - mv build/libs/salary-plus-jhipster-*.jar ./
#      - cp .server/Procfile.dev Procfile
artifacts:
  files:
    - salary-plus-jhipster-*.jar # 업로드할 파일들
#    - Procfile
#  discard-paths: yes # 파일명 기준으로만 업로드
cache:
  paths:
    - '/root/.m2/**/*' # S3 cache에 등록할 파일들
